# Generated by Django 5.2.7 on 2025-11-17 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="user",
        ),
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="supplier",
        ),
        migrations.AddField(
            model_name="brand",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="core.supplier",
                verbose_name="Proveedor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.brand",
                verbose_name="Marca",
            ),
        ),
    ]
