# Generated by Django 5.2.7 on 2025-11-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_purchase_purchasedetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasedetail",
            old_name="quantify",
            new_name="quantity",
        ),
    ]
