# Generated by Django 5.2.7 on 2025-11-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_rename_quantify_purchasedetail_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasedetail",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="purchasedetail",
            name="product",
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="PurchaseDetail",
        ),
    ]
