# Generated by Django 5.2.7 on 2025-11-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("sueldo", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("tasa", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interes",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "monto_pagar",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("numero_cuotas", models.PositiveIntegerField(default=1)),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendiente"),
                            ("PAG", "Pagado"),
                            ("ANU", "Anulado"),
                        ],
                        default="PEND",
                        max_length=4,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.empleado",
                    ),
                ),
                (
                    "tipo_prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.tipoprestamo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrestamoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cuota", models.PositiveIntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("valor_cuota", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saldo_cuota", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="nomina.prestamo",
                    ),
                ),
            ],
        ),
    ]
