# Generated by Django 5.2.7 on 2025-11-01 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=-2025, max_length=10, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (por ejemplo: 0991234567 o 042345678).', regex='^(0[2-9]\\d{7,8})$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (por ejemplo: 0991234567 o 042345678).', regex='^(0[2-9]\\d{7,8})$')]),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Articulo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Categoria')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Articulo')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Costo Producto')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(default=100, help_text='Stock debe estar en 0 y 10000 unidades', verbose_name='Stock')),
                ('iva', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (15, '15%')], default=15, verbose_name='IVA')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Caducidad')),
                ('line', models.CharField(choices=[('RS', 'Rio Store'), ('FS', 'Ferrisariato'), ('CS', 'Comisariato')], default='CS', max_length=2, verbose_name='Linea')),
                ('image', models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('B', 'De Baja')], default='A', verbose_name='Activo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.brand', verbose_name='Marca')),
                ('categories', models.ManyToManyField(to='core.category', verbose_name='Categoria')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='Proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['description'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['description'], name='core_brand_descrip_5b1a81_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['description'], name='core_catego_descrip_509ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='core_produc_descrip_f55423_idx'),
        ),
    ]
