# Generated by Django 5.2.7 on 2025-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_phone_alter_supplier_phone_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
