# Generated by Django 5.2.7 on 2025-11-07 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_customer_phone_alter_supplier_phone_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('EF', 'Efectivo'), ('CH', 'Cheque'), ('TJ', 'Tarjeta'), ('CR', 'Crédito')], default='EF', max_length=2, verbose_name='Metodo de Pago')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Emision')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Iva')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Pago')),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Cambio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, verbose_name='Activo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='core.customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ('-issue_date', 'customer'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='commerce.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product', to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Factura Detalle',
                'verbose_name_plural': 'Factura Detalles',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='commerce_in_issue_d_5e32e1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='commerce_in_custome_24c216_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicedetail',
            index=models.Index(fields=['id'], name='commerce_in_id_26b6b6_idx'),
        ),
    ]
